from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('material/<str:name>/', views.material_detail, name='material_detail'),

    #
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('sell/', views.sell_page, name='sell'),
    path('logout/', views.logout_page, name='logout'),
    path('buy/', views.buy_page, name='buy'),
    path('login-options/', views.login_options, name='login_options'),
    path('register-options/', views.register_options, name='register_options'),
    path('buyer-register/', views.buyer_register, name='buyer_register'),
    path('seller-login/', views.login_page, name='seller_login'),
    path('buyer-login/', views.buyer_login, name='buyer_login'),
    path('buyer-dashboard/', views.buyer_dashboard, name='buyer_dashboard'),
    path('buy-request/<int:waste_id>/', views.buy_request, name='buy_request'),    
    path( 'seller-dashboard/', views.seller_dashboard,name='seller_dashboard'),
    path('approve-request/<int:request_id>/',views.approve_request,name='approve_request'),
    path('reject-request/<int:request_id>/',views.reject_request,name='reject_request'),
    path('buyer-profile/', views.buyer_profile, name='buyer_profile'),
    path('seller-requests/<int:waste_id>/', views.seller_requests, name='seller_requests'),
    path('update-request-status/<int:request_id>/<str:status>/', views.update_request_status),
    path('seller-profile/',views.seller_profile),
    path(  'seller-profile/', views.seller_profile,name='seller_profile'),
    path('seller-settings/', views.seller_settings, name='seller_settings'),
    path('delete-waste/<int:waste_id>/',views.delete_waste,  name='delete_waste'),
    path( 'edit-waste/<int:waste_id>/', views.edit_waste),
    path( 'buyer-profile/', views.buyer_profile ),
    path('cancel-request/<int:request_id>/',views.cancel_request),
    path('buyer-settings/',views.buyer_settings),
    path('seller-notifications/',views.seller_notifications, name='seller_notifications'),
    path('seller-history/',views.seller_history),
    path('buyer-history/',views.buyer_history),
    path('admin-dashboard/', views.admin_dashboard),
    path('all-sellers/', views.all_sellers),
    path('all-buyers/', views.all_buyers),
    path('all-waste/', views.all_waste),
    path('all-requests/', views.all_requests),
    path('pending-requests/', views.pending_requests),
    path( 'approved-requests/', views.approved_requests, name='approved_requests' ),
    path( 'contact/', views.contact, name='contact' ),
    path( 'contact-messages/', views.contact_messages, name='contact_messages' ),
    path('my-messages/',views.my_messages,name='my_messages'),
    path('my-messages/',views.my_messages,name='my_messages'),
    path('delete-message/<int:id>/', views.delete_message, name='delete_message'),
    path('buyer-notifications/',views.buyer_notifications),
    path('services/',views.services,name='services'),
    path( 'about/', views.about, name='about' ),


] 
