# Generated by Django 6.0.4 on 2026-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
