# Generated by Django 6.0.4 on 2026-05-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_buyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
