# Generated by Django 6.0.4 on 2026-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_buyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='waste',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='waste',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
