# Generated by Django 6.0.4 on 2026-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_waste_city_waste_pincode_waste_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='buyer',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
