# Generated by Django 6.0.4 on 2026-05-16 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_buyer_city_buyer_pincode_buyer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='waste',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
