# Generated by Django 6.0.4 on 2026-05-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_waste_created_at_waste_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='original_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
