# Generated by Django 6.0.4 on 2026-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_waste_original_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
