# Generated by Django 6.0.4 on 2026-05-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_buyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
    ]
