# Generated by Django 6.0.4 on 2026-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_buyrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='seller_id',
            field=models.IntegerField(default=0),
        ),
    ]
