# Generated by Django 6.0.4 on 2026-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_waste_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='Not Added'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
