# Generated by Django 6.0.4 on 2026-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_address_user_city_user_pincode_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
