# Generated by Django 6.0.4 on 2026-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='buyer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
