# Generated by Django 6.0.4 on 2026-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contact_buyer_id_contact_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_reply',
            field=models.TextField(default='No Reply Yet'),
        ),
    ]
